### ISSUE TITLE
cmu_auth fails to populate request URL

### ISSUE THREAD

**Issue by justingallagher** [willcrichton/cmu_auth#3]
When requesting a page, the following traceback is given:

```
Traceback (most recent call last):
  File "/usr/local/bin/cmu_auth", line 4, in <module>
    __import__('pkg_resources').run_script('cmu-auth==0.1.6', 'cmu_auth')
  File "/usr/local/lib/python3.4/dist-packages/setuptools-18.5-py3.4.egg/pkg_resources/__init__.py", line 742, in run_script
  File "/usr/local/lib/python3.4/dist-packages/setuptools-18.5-py3.4.egg/pkg_resources/__init__.py", line 1667, in run_script
  File "/usr/local/lib/python3.4/dist-packages/cmu_auth-0.1.6-py3.4.egg/EGG-INFO/scripts/cmu_auth", line 28, in <module>
    s = cmu_auth.authenticate(url, username, password)
  File "/usr/local/lib/python3.4/dist-packages/cmu_auth-0.1.6-py3.4.egg/cmu_auth/auth.py", line 58, in authenticate
    s.post(parser.url, data=parser.to_post).content
  File "/home/justin/.local/lib/python3.4/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/justin/.local/lib/python3.4/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/home/justin/.local/lib/python3.4/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/justin/.local/lib/python3.4/site-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/home/justin/.local/lib/python3.4/site-packages/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

Someone using the Course-API discovered this issue ([here](https://github.com/ScottyLabs/course-api/issues/27)). Here's the URLs I've tried (all failing):

```
https://s3.andrew.cmu.edu/sio/index.html
https://enr-apps.as.cmu.edu/audit/audit
https://cmu.smartevals.com/secure/Login.aspx
```

**Comment by bryanyan** [comment]
I think its because the 'https://login.cmu.edu/idp/Authn/Stateless' page is broken, you get some apache tomcat 404 when accessing the page now. i used an internet archive (last logged 12/20) and it should look like the regular sio/blackboard/gmail cmu login page when you try and access it. maybe cmu moved it or changed something?
